version: '1.0'

services:
  postgres:
    image: postgres:17
    container_name: nest_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nest-app:
    build: .
    container_name: nest_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/crypto_db?schema=public"
    ports:
      - "3000:3000"
    command: ["sh", "-c", "pnpm install --frozen-lockfile && pnpm prisma migrate deploy && pnpm prisma generate && pnpm start"]

volumes:
  postgres_data:
